### ISSUE TITLE
panic: crypto/cipher: input not full blocks

### ISSUE THREAD

**Issue by zvictorp** [TRON-US/go-btfs#1217]
Dear team

I cannot do anything with my in-app wallet. Neither change or validate password, nor transfer to another wallet.

I always get the same error:

For example, if I try to change default password, I get the following output:

```
 ./btfs wallet password "xxxxxxxx" -p "."
panic: crypto/cipher: input not full blocks

goroutine 46 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0xc001a7fc70, 0xc000235ad0, 0x24, 0x24, 0xc000235a10, 0x24, 0x24)
        /usr/local/go/src/crypto/cipher/cbc.go:119 +0x4e9
github.com/TRON-US/go-btfs/core/wallet.DecryptWithAES(0x7ffce8c2d86e, 0x1, 0xc0001e4330, 0x30, 0xc0019205a0, 0xc001a0a000, 0x0, 0x0)
        /go-btfs/core/wallet/aes.go:50 +0x252
github.com/TRON-US/go-btfs/core/commands.validatePassword(0xc001a0a000, 0x7ffce8c2d86e, 0x1, 0x8, 0xc001920628)
        /go-btfs/core/commands/wallet.go:538 +0x50
github.com/TRON-US/go-btfs/core/commands.glob..func186(0xc00014ecb0, 0x381f920, 0xc001965040, 0x26752e0, 0xc0019262a0, 0x0, 0x0)
        /go-btfs/core/commands/wallet.go:347 +0x38b
github.com/TRON-US/go-btfs-cmds.(*executor).Execute.func2(0xc001926360, 0x4628620, 0xc00014ecb0, 0x381f920, 0xc001965040, 0x26752e0, 0xc0019262a0)
        pkg/mod/github.com/!t!r!o!n-!u!s/go-btfs-cmds@v0.2.13/executor.go:80 +0x66
created by github.com/TRON-US/go-btfs-cmds.(*executor).Execute
        pkg/mod/github.com/!t!r!o!n-!u!s/go-btfs-cmds@v0.2.13/executor.go:79 +0x1b2 
```
```
 ./btfs wallet transfer -p "." TRZxhvsgwWbW8rQvAoN55fnxZaESMB3teF 1000000000
panic: crypto/cipher: input not full blocks

goroutine 48 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0xc00068dae0, 0xc0001b5ad0, 0x24, 0x24, 0xc0001b5a10, 0x24, 0x24)
        /usr/local/go/src/crypto/cipher/cbc.go:119 +0x4e9
github.com/TRON-US/go-btfs/core/wallet.DecryptWithAES(0x7ffe7c25a840, 0x1, 0xc000164b10, 0x30, 0xc001a15440, 0xc00550e000, 0x0, 0x0)
        /go-btfs/core/wallet/aes.go:50 +0x252
github.com/TRON-US/go-btfs/core/commands.validatePassword(0xc00550e000, 0x7ffe7c25a840, 0x1, 0x8, 0xc001a154c8)
        /go-btfs/core/commands/wallet.go:538 +0x50
github.com/TRON-US/go-btfs/core/commands.glob..func190(0xc001a2e9a0, 0x381f920, 0xc005502320, 0x26752e0, 0xc001a3c0c0, 0x0, 0x0)
        /go-btfs/core/commands/wallet.go:496 +0x145
github.com/TRON-US/go-btfs-cmds.(*executor).Execute.func2(0xc001a3c180, 0x4628bc0, 0xc001a2e9a0, 0x381f920, 0xc005502320, 0x26752e0, 0xc001a3c0c0)
        pkg/mod/github.com/!t!r!o!n-!u!s/go-btfs-cmds@v0.2.13/executor.go:80 +0x66
created by github.com/TRON-US/go-btfs-cmds.(*executor).Execute
        pkg/mod/github.com/!t!r!o!n-!u!s/go-btfs-cmds@v0.2.13/executor.go:79 +0x1b2
```

Please, help me to  handle it.

Thank you.

**Comment by Sophia-yu-kk** [comment]
What system are you on, what version of the go-btfs executable, where did you source the program, did you download it yourself, or did you compile it?

**Comment by zvictorp** [comment]
> What system are you on, what version of the go-btfs executable, where did you source the program, did you download it yourself, or did you compile it?

Ubuntu 18.04.3 LTS

```
./btfs id
{
        "ID": "16Uiu2HAm5ce3ayTvyC3CrmVi6ydbczTRR54sWwrs9PeBhEzVDSXn",
        "PublicKey": "CAISIQKXZBIZecA+zciEYsZKfKpGd0D3Nbd/VsCjegxKMOmA/Q==",
        "Addresses": null,
        "AgentVersion": "go-btfs/1.6.0/18b4d80",
        "ProtocolVersion": "btfs/0.1.0",
        "Protocols": null,
        "DaemonProcessID": -1,
        "TronAddress": "TUoqh9dPze1fiG9BHWoX6tCeU3PbeSpdiu"
}
```
go-btfs installed according to the official installation manual https://docs.btfs.io/docs/btfs-demo (install.sh was downloaded and launched).

**Comment by Sophia-yu-kk** [comment]
Please try compiling one with the code and post the compiled doc

**Comment by zvictorp** [comment]
It does not even start after installation

```
root@str1:~/go/bin# btfs init
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.0/unsafe.go:20 +0x132
```

**Comment by Sophia-yu-kk** [comment]
We are sorry that we did not reproduce your question. We suggest you try a different computer.
