### ISSUE TITLE
node keep crashing

### ISSUE THREAD

**Issue by bartoszn** [TRON-US/go-btfs#628]
#### Version information:
go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/linux
Golang version: go1.14.6

#### Description:
Node is running and at some point start showing errors 
_"Failed to sync host stats: open /home/btfs/.btfs/datastore: too many open files"_

and at some point crash and exit

2020-08-06T21:13:57.713Z        ERROR   spin    spin/hosts.go:63        Failed to sync host stats: open /home/btfs/.btfs/datastore: too many open files
2020-08-06T21:44:12.490Z        ERROR   spin    spin/hosts.go:63        Failed to sync host stats: open /home/btfs/.btfs/datastore: too many open files
2020-08-07T00:14:13.519Z        ERROR   spin    spin/hosts.go:63        Failed to sync host stats: open /home/btfs/.btfs/datastore: too many open files
panic: runtime error: index out of range [0] with length 0

goroutine 3520 [running]:
github.com/TRON-US/go-btfs/spin.(dcWrap).update(0xc0012be1e0, 0xc000eae1e0, 0x0, 0x0, 0x0)
        /go-btfs/spin/analytics.go:154 +0xa37
github.com/TRON-US/go-btfs/spin.(dcWrap).doPrepData(0xc0012be1e0, 0xc000eae1e0, 0x8, 0x2e0d1b0, 0xc02a262360, 0xc003f87180, 0x1869f12, 0x2e0fa40)
        /go-btfs/spin/analytics.go:219 +0x4d
github.com/TRON-US/go-btfs/spin.(dcWrap).sendData(0xc0012be1e0, 0xc000eae1e0, 0xc00090a800)
        /go-btfs/spin/analytics.go:186 +0x50
github.com/TRON-US/go-btfs/spin.(dcWrap).collectionAgent(0xc0012be1e0, 0xc000eae1e0)
        /go-btfs/spin/analytics.go:274 +0xca
created by github.com/TRON-US/go-btfs/spin.Analytics
        /go-btfs/spin/analytics.go:125 +0x4cd

after restart it was live few hours and crash again, I'll not mention that after every restart timeout and score going down which was 10/10....

2020-08-08T00:59:39.395Z        ERROR   spin    spin/hosts.go:63        Failed to sync host stats: open /home/btfs/.btfs/datastore: too many open files
panic: runtime error: index out of range [0] with length 0

goroutine 2206 [running]:
github.com/TRON-US/go-btfs/spin.(*dcWrap).update(0xc0013176a0, 0xc00020c3c0, 0x0, 0x0, 0x0)
        /go-btfs/spin/analytics.go:154 +0xa37
github.com/TRON-US/go-btfs/spin.(*dcWrap).doPrepData(0xc0013176a0, 0xc00020c3c0, 0x2e0d1e8, 0xc02bc4d0f0, 0xc03386c080, 0xc0000e4380, 0xc00055f4d0, 0x2e0fa40)
        /go-btfs/spin/analytics.go:219 +0x4d
github.com/TRON-US/go-btfs/spin.(*dcWrap).sendData(0xc0013176a0, 0xc00020c3c0, 0xc000098000)
        /go-btfs/spin/analytics.go:186 +0x50
github.com/TRON-US/go-btfs/spin.(*dcWrap).collectionAgent(0xc0013176a0, 0xc00020c3c0)
        /go-btfs/spin/analytics.go:274 +0xca
created by github.com/TRON-US/go-btfs/spin.Analytics
        /go-btfs/spin/analytics.go:125 +0x4cd

**Comment by taiyangc** [comment]
Thank you for the crash report. We are looking into it. In the meantime, could you make sure that you have enough storage under `/home/btfs/.btfs/` ?

**Comment by bartoszn** [comment]
Hi,
I have that on fresh setup, there is only 1% drive space used

Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           393M   40M  354M  11% /run
/dev/sda2       1.8T  1.6G  1.7T   1% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           393M     0  393M   0% /run/user/1000


today morning when I checked it was cras again

2020-08-10T04:15:14.842Z        ERROR   spin    spin/hosts.go:63
 Failed to sync host stats: open /home/btfs/.btfs/datastore: too many open
files
panic: runtime error: index out of range [0] with length 0

goroutine 1713 [running]:
github.com/TRON-US/go-btfs/spin.(*dcWrap).update(0xc000fc4160,
0xc0011d61e0, 0x0, 0x0, 0x0)
        /go-btfs/spin/analytics.go:154 +0xa37
github.com/TRON-US/go-btfs/spin.(*dcWrap).doPrepData(0xc000fc4160,
0xc0011d61e0, 0x13, 0xc024872360, 0xc010722080, 0xc001408700, 0xc025d10dd0,
0x2e0fa40)
        /go-btfs/spin/analytics.go:219 +0x4d
github.com/TRON-US/go-btfs/spin.(*dcWrap).sendData(0xc000fc4160,
0xc0011d61e0, 0xc000a62800)
        /go-btfs/spin/analytics.go:186 +0x50
github.com/TRON-US/go-btfs/spin.(*dcWrap).collectionAgent(0xc000fc4160,
0xc0011d61e0)
        /go-btfs/spin/analytics.go:274 +0xca
created by github.com/TRON-US/go-btfs/spin.Analytics
        /go-btfs/spin/analytics.go:125 +0x4cd

Thanks,
Bartosz

**Comment by taiyangc** [comment]
@bartoszn Mind showing the output of `ls -l /home/btfs/.btfs/datastore`? Thanks.

**Comment by bartoszn** [comment]
ls -l /home/btfs/.btfs/datastore

total 9780
-rw-r--r-- 1 btfs btfs  458792 Aug 10 21:25 000076.ldb
-rw-r--r-- 1 btfs btfs 2140816 Aug 11 00:21 000079.ldb
-rw-r--r-- 1 btfs btfs  710131 Aug 11 00:21 000080.ldb
-rw-r--r-- 1 btfs btfs 3801421 Aug 11 08:09 000081.log
-rw-r--r-- 1 btfs btfs 2849298 Aug 11 02:24 000082.ldb
-rw-r--r-- 1 btfs btfs      16 Aug 10 21:25 CURRENT
-rw-r--r-- 1 btfs btfs      16 Aug 10 21:25 CURRENT.bak
-rw-r--r-- 1 btfs btfs       0 Aug  6 15:49 LOCK
-rw-r--r-- 1 btfs btfs   20214 Aug 11 02:24 LOG
-rw-r--r-- 1 btfs btfs    2307 Aug 11 02:24 MANIFEST-000078
